### PR TITLE
daos cleanup

### LINKED ISSUE #350: daos: double check errors in daos_read/write
I think our daos_read() and daos_write() have a couple of things to fix.

We are setting ```rc = -1``` here on errors, but then we return ```got_size``` no matter what.
https://github.com/hpc/mpifileutils/blob/a059f299c3b0d4f4409a0ce48360a1081645d1b4/src/common/mfu_io.c#L793

Also, we're updating the offset, even on error cases.  Not sure if that's correct to do or not (depends on got_size).
https://github.com/hpc/mpifileutils/blob/a059f299c3b0d4f4409a0ce48360a1081645d1b4/src/common/mfu_io.c#L795

### PR DESCRIPTION
**Pull request by dsikich**
Fixes for issue #350 and #351 

Signed-off-by: Danielle Sikich <danielle.sikich@intel.com>

### CODE REVIEW

**Comment by dsikich** [comment]
@adammoody in response to issue #350

**Comment by dsikich** [comment]
@adammoody these two commits fix issues #350 and #351 for daos_read and daos_write.

**Comment by adammoody** [comment]
Wow, that's looking really clean.  Thanks, @dsikich .

**Comment by dsikich** [comment]
> Wow, that's looking really clean. Thanks, @dsikich .

@adammoody yes thanks looks much better 👍

**Pull request merged**
