### PR TITLE
test : add test case for dcp against FIEMAP

### PR DESCRIPTION
**Pull request by KnightKu**
Signed-off-by: Gu Zheng <gzheng@ddn.com>

### CODE REVIEW

**Comment by adammoody** [comment]
@dsikich Since you're familiar with dcmp and the testing infrastructure, can you review this PR?

**Comment by dsikich** [comment]
@adammoody Yes, I can do that. Do you also want me to review the additions they made to the test_dcmp script? There is also a pull request for that.

**Comment by adammoody** [comment]
Yes, that'd be helpful too.  Thanks!

**Comment by dsikich** [comment]
I actually checked on the test_octal.py script I added to nose2, and I forgot to pass in the variables to the script as well. I'm sure there are many ways to do this, but below I added the first way that worked for me.
 
Also, the dchmod_path is the only variable used in the actual bash script, the mpifu_path variable I just used to make it easier to change the call path to the script

#!/usr/bin/env python2
import subprocess
 
# chane your path here as necessary  
mpifu_path  = "~/mpifileutils/test/tests/test_dchmod/test_octal.sh"
dchmod_path = "~/mpifileutils/install/bin/dchmod"
 
def test_octal():
p = subprocess.Popen(["%s %s" % (mpifu_path, dchmod_path)], shell=True, executable="/bin/bash").communicate()

**Pull request merged**
