### PR TITLE
dcp: Added options (-G, -U) to set effective GID/UID to perform copy

### PR DESCRIPTION
**Pull request by bdevcich-hpe**
Signed-off-by: Blake Devcich <blake.devcich@hpe.com>

### CODE REVIEW

**Comment by bdevcich-hpe** [comment]
@adammoody, I'm unable to add reviewers to this PR. Could you add whoever is appropriate?

**Comment by bdevcich-hpe** [comment]
This is required for the https://github.com/NearNodeFlash/ project.

**Comment by adammoody** [comment]
Thanks for the contribution and explanation, @bdevcich-hpe .  This looks good in a quick glance.  I'll take a deeper look soon.

**Review by adammoody — APPROVED** [review]

**Comment by adammoody** [comment]
Thanks, @bdevcich-hpe .

**Pull request merged**
