### PR TITLE
daos: style updates

### PR DESCRIPTION
**Pull request by adammoody**
Signed-off-by: Adam Moody <moody20@llnl.gov>

### CODE REVIEW

**Comment by adammoody** [comment]
@dsikich , I took another style sweep: change 8-space indents to 4, drop some tab characters, drop some unnecessary "*" dereferences.  I also moved some lines around.  However, I don't have a DAOS install that I can compile and test against.

Would you mind testing this out for me to make sure I didn't break anyting?

In particular, take a close look at the lines where I changed from pointers to non-pointers.  It seems the uuid_t type is a pointer internally, so it can often be passed around without the extra "&" and "*" characters.

If you find any changes, you should be able to push directly to this daosstyle branch.

Thanks!

**Comment by dsikich** [comment]
@adammoody yes no problem, will run my tests on this branch on Monday before working on any of the other tickets so the style stuff can get merged first.

**Comment by dsikich** [comment]
@adammoody I built and ran my tests and looks good.

**Comment by adammoody** [comment]
Thank you @dsikich .

**Pull request merged**
