### PR TITLE
hdf5: find and define the hdf5 bin directory

### PR DESCRIPTION
**Pull request by daltonbohning**
Signed-off-by: Dalton Bohning <daltonx.bohning@intel.com>

### CODE REVIEW

**Comment by dsikich** [comment]
@daltonbohning thanks, I will merge this into my hdf5 PR after we merge in the serialization changes that add HDF5 support

**Review by adammoody — APPROVED** [review]
Looks good.  Thanks @daltonbohning

**Comment by dsikich** [comment]
@daltonbohning the serialization PR must have generated some conflicts here after it was merged.

**Comment by daltonbohning** [comment]
> @daltonbohning the serialization PR must have generated some conflicts here after it was merged.

@dsikich Yeah, I'll just delete this PR and instead create a PR directly into master. Thanks!

**Pull request closed without merging**
