### PR TITLE
Update DAOS-Support.md

### PR DESCRIPTION
**Pull request by rajkumarpatel2602**
Fix broken link

Signed-off-by: Rajkumar Patel <rajkumar.patel@segate.com>

### CODE REVIEW

**Comment by dsikich** [comment]
@rajkumarpatel2602 Hi, sorry about this. I just submitted a PR to fix this link the other day. It should be merged now. Thanks!

**Comment by rajkumarpatel2602** [comment]
> @rajkumarpatel2602 Hi, sorry about this. I just submitted a PR to fix this link the other day. It should be merged now. Thanks!

Oh, That's great @dsikich!
Thanks.

**Comment by adammoody** [comment]
Thanks @rajkumarpatel2602 and @dsikich .  Good to close out this PR since we merged @dsikich 's fix?

**Comment by dsikich** [comment]
@adammoody yeah, we can close this, the link is working now.

**Pull request closed without merging**
