### PR TITLE
dsync: link-dest edits

### PR DESCRIPTION
**Pull request by adammoody**
Signed-off-by: Adam Moody <moody20@llnl.gov>

### CODE REVIEW

**Comment by adammoody** [comment]
@KnightKu , I'm nearly done with the edit sweep.  I added some comments, shortened some variable names, renamed some variables, and reordered some lines to help new readers better understand the code.

Would you please give this a fresh look?

Also, do you have some tests you can run my updated version against to make sure I didn't break anything?

**Comment by KnightKu** [comment]
Hi Adam,
Thanks for helping to improve it.
I didn't look much into the code (sorry, quite busy with other stuff now), so just ran some simple tests, but failed with segment fault.
# ./src/dsync/dsync /tmp/src/ --link-dest /tmp/link_dest1/ /tmp/link_dest2/
[2019-06-17T14:31:12] Warning: `/tmp/link_dest2/' does not exist
[2019-06-17T14:31:12] Walking source path
[2019-06-17T14:31:12] Walking /tmp/src
[2019-06-17T14:31:12] Walked 169 items in 0.002717 seconds (62206.000527 files/sec)
[2019-06-17T14:31:12] Walking destination path
[2019-06-17T14:31:12] Walking /tmp/link_dest2
[2019-06-17T14:31:12] Walked 0 items in 0.000414 seconds (0.000000 files/sec)
[2019-06-17T14:31:12] Walking link-dest path
[2019-06-17T14:31:12] Walking /tmp/link_dest1
[2019-06-17T14:31:12] Walked 169 items in 0.002161 seconds (78212.222884 files/sec)
[2019-06-17T14:31:12] Comparing file sizes and modification times of 94 items with link dest
Segmentation fault (core dumped)

**Comment by adammoody** [comment]
@KnightKu , thanks for testing.  Ugh, it had passed the few test cases I threw at it.  I'll try again and take a closer look.

In case I can't reproduce this, do you have a stack trace that you can send along?

Or can you describe the test set up, i.e., the set of source, link-dest, and target directory files?

**Comment by adammoody** [comment]
@KnightKu , got a segfault to reproduce and tracked that down to some bad summarize calls.  I pushed a fix for that one.

Can you please try again with your test case?  Thanks.

**Comment by KnightKu** [comment]
Hi Adam,
Just a quick test, It works now. 
And code changes, look good to me.

**Comment by adammoody** [comment]
Thanks, @KnightKu .

**Pull request merged**
